apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-exporter
  namespace: rabbits
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-exporter
  template:
    metadata:
      labels:
        app: rabbitmq-exporter
    spec:
      containers:
      - name: rabbitmq-exporter
        image: kbudde/rabbitmq-exporter:latest
        ports:
        - name: metrics
          containerPort: 9090
        env:
        - name: RABBITMQ_URL
          value: "http://rabbitmq-0.rabbitmq:15672" # Adjust URL according to your RabbitMQ service
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: rabbits
spec:
  selector:
    app: rabbitmq-exporter
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
