apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-exporter
  namespace: monitoring
spec:
  selector:
    app: rabbitmq-exporter
  ports:
  - protocol: TCP
    port: 9419
    targetPort: 9419
